DROP INDEX IF EXISTS idx_audit_logs_created_at;
DROP INDEX IF EXISTS idx_bookings_user;
DROP INDEX IF EXISTS idx_bookings_room_time;
DROP INDEX IF EXISTS idx_rooms_capacity;

ALTER TABLE IF EXISTS bookings DROP CONSTRAINT IF EXISTS no_booking_overlap;
ALTER TABLE IF EXISTS bookings DROP CONSTRAINT IF EXISTS unique_bookings;
ALTER TABLE IF EXISTS bookings DROP CONSTRAINT IF EXISTS chk_bookings_status;
ALTER TABLE IF EXISTS bookings DROP CONSTRAINT IF EXISTS chk_bookings_time;
ALTER TABLE IF EXISTS bookings DROP CONSTRAINT IF EXISTS fk_bookings_user;
ALTER TABLE IF EXISTS bookings DROP CONSTRAINT IF EXISTS fk_bookings_room;
ALTER TABLE IF EXISTS bookings DROP CONSTRAINT IF EXISTS pk_bookings;

ALTER TABLE IF EXISTS audit_logs DROP CONSTRAINT IF EXISTS chk_audit_logs_action;
ALTER TABLE IF EXISTS audit_logs DROP CONSTRAINT IF EXISTS fk_audit_logs_user;
ALTER TABLE IF EXISTS audit_logs DROP CONSTRAINT IF EXISTS pk_audit_logs;

ALTER TABLE IF EXISTS rooms DROP CONSTRAINT IF EXISTS chk_rooms_capacity;
ALTER TABLE IF EXISTS rooms DROP CONSTRAINT IF EXISTS chk_rooms_name;
ALTER TABLE IF EXISTS rooms DROP CONSTRAINT IF EXISTS unique_rooms_name;
ALTER TABLE IF EXISTS rooms DROP CONSTRAINT IF EXISTS pk_rooms;

ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS chk_users_role;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS chk_users_password;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS chk_users_username;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS unique_users_username;
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS pk_users;

DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS btree_gist;
